# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cdd9e214012aed106f329e12a2d933a86af89951963a5b73f714763bf7ae6c7c5cc1ed70496c78e578c4967969220288f6dcc8e0ae47d305dd3e83138631f296
  filestack_api_key: <%= ENV['FILESTACK_API_KEY'] %>

test:
  secret_key_base: d602326830282903b8478c70a97c2492a95ca88b43b251fccfce6bdd34d7b1d1d02cffee69eb99dfc86cdb0219cb4a130c35cdd9c219a43eefd4aa9340e2abd5
  filestack_api_key: <%= ENV['FILESTACK_API_KEY'] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  filestack_api_key: <%= ENV['FILESTACK_API_KEY'] %>
